apiVersion: v1
kind: Service
metadata:
  name: service-set
  labels:
    app: mi-set
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: mi-set
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mi-set
spec:
  selector:
    matchLabels:
      app: mi-set
  replicas: 3
  serviceName: service-set #seguir metada y cuantos pods se lanza
  template:
    metadata:
      labels:
        app: mi-set
    spec:
      containers:
      - name: nginx
        image: nginx:1.19-alpine
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html/data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
          #multiple deficiones seprandolas con --- para yaml