apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-escalado
  labels:
    app: aplicacion-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aplicacion-2
  template:
    metadata:
      labels:
        app: aplicacion-2
    spec:
      containers:
      - name: nginx
        image: nginx:1.20-alpine
        ports:
        - containerPort: 80