apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nuestro-daemonset
  labels:
    app: aplicacion-logs
spec:
  selector:
    matchLabels:
      app: aplicacion-logs
  template:
    metadata:
      labels:
        app: aplicacion-logs
    spec:
      containers:
      - name: fluent
        image: fluent/fluentd:edge
        ports:
        - containerPort: 24224
    # no se definen replicas
    # lanza nodos que se necesite
    #kubectl delete pod nuestro-daemonset-46wb8 y crea automaticamente otro  
    # para losg vpn copia de segurida un pod en cada nodo