apiVersion: v1
kind: ConfigMap
metadata:
  name: config-web
data:
  # Clave-valor
  mensaje: "Mensaje configurado: buenos días"
  port: "80"
  database: "mysql://localhost:3306/aplicacion"
  # Fichero / Multilinea
  default.conf.template: |
    server {
        listen       8080;
        server_name  localhost;
    
        location / {
            return 200 '${MENSAJE}';
        }
    
    }

