apiVersion: v1
kind: Service
metadata:
  name: servicio-configmap
spec:
  type: NodePort
  selector:
    app: web-configurada
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008